name: "faster-whisper-large-v3"
backend: "python"
max_batch_size: 1
input [
  {
    name: "AUDIO"
    data_type: TYPE_UINT8
    dims: [ -1 ]    # variable-length 1D array of bytes
  }
]
output [
  {
    name: "TRANSCRIPTION"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
