name: "faster-whisper-large-v3"
backend: "python"
max_batch_size: 1
input [
  {
    name: "AUDIO"
    data_type: TYPE_UINT8
    dims: [ -1 ]    # variable-length 1D array of bytes
  }
]
output [
  {
    name: "TRANSCRIPTION"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "WAVEFORM"
    data_type: TYPE_INT16
    dims: [ -1 ]
  },
  {
    name: "DURATION"
    data_type: TYPE_FP32
    dims: [ 1 ] 
  }
]
